### ISSUE TITLE
xib内的子uiview进行updateCornerRadius会有问题

### ISSUE THREAD

**Issue by yanxuetongxue** [qinqi777/QQCorner#1]
cell中有 view，cell屏幕宽。不会按照实际的屏幕去 trailing Space to。 计算view的宽度按照xib内cell设置的大小(如320- trailing Space to)。

**Comment by yanxuetongxue** [comment]
change desc

**Comment by qinqi777** [comment]
这个问题，你需要在能获取到view正确frame的情况下再update，例如 -layoutSubviews 方法。因为我没有监听view的frame变化，所以方法名才是update的，要不就可以是add了。因为-layoutSubviews方法的调用频率太过频繁了。

**Comment by qinqi777** [comment]
我这个添加圆角的原理其实是在view上添加了一个layer，但是layer并不会随着view的frame变化而变化。也就是说，view的frame变化时，你就要update一下。
