### ISSUE TITLE
总是报错[Unknown process name] clip: invalid context 0x0.

### ISSUE THREAD

**Issue by cuixinle** [qinqi777/QQCorner#10]
[Unknown process name] clip: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by qinqi777** [comment]
Xcode菜单栏 -> Product -> Scheme - > Edit Scheme -> Run -> Arguments
在下面的 Environment Variables 这一栏，添加一行
Name：OS_ACTIVITY_MODE
Value：disable
然后在前面打上勾，close，再重新运行一下

**Comment by DSPerson** [comment]
#11 我尝试解决了 你们可以试试。。
