### ISSUE TITLE
uiview加圆角报警告:[Unknown process name] CGContextAddPath: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

### ISSUE THREAD

**Issue by obama901** [qinqi777/QQCorner#3]
如题,无效的上下文.
for example:
`- (UIView *)smartKeyFootView`
`{`
    `UIView *footView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, MAIN_SIZE.width, RELATIVE_HEIGHT(10))];`
    `UIView *helfCornerView = [[UIImageView alloc]init];`
    `helfCornerView.frame = CGRectMake(RELATIVE_WIDTH(16.5), 0, RELATIVE_WIDTH(342), RELATIVE_HEIGHT(6));`
    `helfCornerView.sakura.backgroundColor(@"Global.circularCellBackgroundColor");`
    `[footView addSubview:helfCornerView];`
    `[helfCornerView updateCornerRadius:^(QQCorner *corner) {`
        `corner.radius = QQRadiusMake(0, 0, RELATIVE_HEIGHT(6), RELATIVE_HEIGHT(6));`
    `}];`    
    `return footView;`
`}`

上面的uiviwe就是用于在`- (UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section`中返回视图的.
一般报警会有两句话:
`2019-02-12 14:53:16.144824+0800 IsolatedSecond[8464:2267719] [Unknown process name] CGContextAddPath: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.`
`2019-02-12 14:53:16.144873+0800 IsolatedSecond[8464:2267719] [Unknown process name] clip: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
`

**Comment by qinqi777** [comment]
这个你不用担心的，如果强迫症还是很在意的话。
打开你的工程，找到Xcode菜单栏，进行如下操作：
Product -> Scheme -> Edit Scheme -> 左边选择 Run，右边上面标签选择 Arguments -> 在Environment Variables(环境变量)添加“OS_ACTIVITY_MODE”，不带引号，Value填写“disable”，不带引号。-> Close
再运行，就好啦

**Comment by obama901** [comment]
好的🤝

**Comment by bigNiuSanMao** [comment]
> 这个你不用担心的，如果强迫症还是很在意的话。 打开你的工程，找到Xcode菜单栏，进行如下操作： Product -> Scheme -> Edit Scheme -> 左边选择 Run，右边上面标签选择 Arguments -> 在Environment Variables(环境变量)添加“OS_ACTIVITY_MODE”，不带引号，Value填写“disable”，不带引号。-> Close 再运行，就好啦

这种方式处理 会把所有的打印信息都关掉了，不可取啊
