### ISSUE TITLE
ios10 以下  CGContextSetLineWidth(context, 1) 是不是不对？

### ISSUE THREAD

**Issue by zzzworm** [qinqi777/QQCorner#4]
> + (UIImage *)imageWithQQCorner:(void (^)(QQCorner *))handler size:(CGSize)size {
    QQCorner *corner = [[QQCorner alloc] init];
    if (handler) {
        handler(corner);
    }
    if (!corner.fillColor) {
        corner.fillColor = [UIColor clearColor];
    }
    UIBezierPath *path = qq_pathWithCornerRadius(corner.radius, size);
    if (@available(iOS 10.0, *)) {
        UIGraphicsImageRenderer *render = [[UIGraphicsImageRenderer alloc] initWithSize:size];
        return [render imageWithActions:^(UIGraphicsImageRendererContext * _Nonnull rendererContext) {
            CGContextSetStrokeColorWithColor(rendererContext.CGContext, corner.borderColor.CGColor);
            CGContextSetFillColorWithColor(rendererContext.CGContext, corner.fillColor.CGColor);
            CGContextSetLineWidth(rendererContext.CGContext, corner.borderWidth);
            [path addClip];
            CGContextAddPath(rendererContext.CGContext, path.CGPath);
            CGContextDrawPath(rendererContext.CGContext, kCGPathFillStroke);
        }];
    } else {
        UIGraphicsBeginImageContext(size);
        CGContextRef context = UIGraphicsGetCurrentContext();
        CGContextSetStrokeColorWithColor(context, corner.borderColor.CGColor);
        CGContextSetFillColorWithColor(context, corner.fillColor.CGColor);
        CGContextSetLineWidth(context, 1);  <--- here

这里没有使用corner.borderWidth，应该是不对的吧？

**Comment by qinqi777** [comment]
是的！感谢反馈！下个版本会修复这个issue

**Comment by qinqi777** [comment]
已经修复
