### ISSUE TITLE
请问如何重置updateCornerRadius

### ISSUE THREAD

**Issue by BadReese** [qinqi777/QQCorner#5]
在cell复用的时候，比如对话CELL
发送方我使用渐变背景
接收方我使用非统一圆角边框

因此想问问有没有方式方便地取消圆角边框 
避免复用的时候出错
谢谢你
很棒的库

**Comment by qinqi777** [comment]
emmm，这样的话，不建议来回去除和添加哦。因为这样的过程其实相当于 addSublayer 和 removeFromSuperLayer 的操作。

建议以下的解决方案：
1、不管是发送方还是接收方，聊天气泡一般都是UI切的图，可以使用平铺或者拉伸的方式，将图片自适应。当然你的背景是渐变色的，参数可能需要好好调校一下。
2、如果你的发送方和接收方是同一个Cell，你可以创建两个UIView，发送方一个，接收方一个。如此一来就控制hidden就好了，当然，每个Cell的大小是不一样的，所以当Cell的大小变化时，还是需要update一下的，通常是在set数据模型的方法中。（不建议在-layoutSubviews里面哦，不然我也不会让用户一直update了~）

根据你的需求，第2个方法是最优方案，虽然调用是一个block，但是里面只是对corner进行属性赋值而已，所以对性能没什么影响的。
至于你说的要不要添加一个移除的方法，下个版本我会考虑的~

**Comment by BadReese** [comment]
好的 谢谢你~

**Comment by BadReese** [comment]
另外我想请问下
比起
不断addSublayer跟removeFromSuperLayer对性能的影响
每个CELL增加一个发送方/接收方的LAYOUT对内存的影响
哪种方案更好呢？为什么？
麻烦指点下

**Comment by qinqi777** [comment]
对于Cell的内容不断变化的情况，我建议给数据模型绑定一个frameModel，Cell持有frameModel，frameModel持有数据模型。这样你在处理UITableView的数据源的时候，就可以把frame或者layout计算好了。
当然是Layout对性能的影响小一些了，因为addSubview时，除去中间的步骤，最终也会调用-layoutSubviews的。

**Comment by BadReese** [comment]
使用发送方跟接收方两种layout的好处就是，避免不同圆角复用的时候，导致圆角度数不正确。
谢谢大佬的库~
