### ISSUE TITLE
你好 cell 添加设置圆角的方法，列表页面出现隐藏，而且列表非常卡，

### ISSUE THREAD

**Issue by pttyy** [qinqi777/QQCorner#7]
<img width="2512" alt="WeChat3767d34b46665ba57d6c52bd99c53a79" src="https://user-images.githubusercontent.com/13176599/61168971-c160e980-a588-11e9-9d9e-bc276c9655a1.png">

**Comment by pttyy** [comment]
我这个列表的cell 是动态行高

**Comment by qinqi777** [comment]
为了性能考虑，每次在view的frame发生变化时，需要调用update方法。
因为你的描述不是很准确，我分析了可能的解决方案，请参考：

① 如果是使用了 UITableView 的 estimatedRowHeight 设置的动态计算行高。
此时，进入Cell中，重写Cell的 - layoutSubviews 方法，别忘了调用super，在此处调用 update圆角的方法。

② 自己做了缓存策略，在 - tableView:heightForRowAtIndexPath 方法中返回行高，也建议第①种情况的解决方案，重写Cell的 - layoutSubviews 方法，别忘了调用super，在此处调用 update圆角的方法。

③ 在 - tableView:cellForRowAtIndexPath 方法中，也就是return cell 之前，改变了Cell的frame，比如setModel时，就是绑定数据源刷新界面的时候改变了frame的话，可以在改变frame之后，调用update方法。

总之，就是找到合适的时机，在cell的frame发生变化时，要调用update方法。
PS：对于UITableViewCell，不建议直接去update cell自身，最少也是要update其contentView，当然，如果添加一个bgView是更好的。因为一般带有圆角的cell之间都会有间距，推荐添加一个bgView来专门处理。

**Comment by pttyy** [comment]
你说的 update 方法是 updateCornerRadius 的方法吧。

**Comment by qinqi777** [comment]
对的，就是-updateCornerRadius方法，刚才截图没有加载出来。

**Comment by pttyy** [comment]
我是用 Masonry 适配的update 必须在 layoutSubviews 方法里吗？调用设置圆角 还没有 cornerRadius 的帧率高，方便加个qq 联系吗？

**Comment by qinqi777** [comment]
如果无法解决的话，就用系统原生的圆角设置一下先。
我认为是跟你设计的视图有关系，这个update方法，应该紧跟着其View的frame发生变化的下一行就调用。如果显示不正常或者异常卡顿，就是调用的时机不对。
另外，你这个圆角是都是8，可以用QQRadiusMakeSame内联函数来创建哦

**Comment by qinqi777** [comment]
另外，如果这个圆角是固定的，那么可以在View初始化的时候，update一下。
然后之后需要更新的时候，update函数的闭包参数可以传入nil
