### ISSUE TITLE
cell 圆角出现问题

### ISSUE THREAD

**Issue by CoderLwcXing** [qinqi777/QQCorner#8]
我在 collectionviewcell 中套用了一个横向展示的 collectionview ，当在横向 collectionviewcell 使用 updateCornerRadius 时是生效了，但是，当滑动后，就导致updateCornerRadius 失效了，之前的圆角都没有了，请大佬解惑，目前我还没找到办法解决

**Comment by qinqi777** [comment]
1.各种嵌套的话，要注意各个视图的背景色
2.如你所说，在CollectionViewCell中，如果你需要使用带圆角的，你可以新建一个UIView放在它的contentView上，然后将contentView的背景色设置为clear，这样你的圆角就是添加在你自己创建的UIView上，这样不影响系统本身的渲染效果会更好一些。因为collectionCell的frame会根据代理方法实时更新的，而我们自己创建的UIView就可以知道其frame或者约束改变的时机，只要在改变之后调用updateCornerRadius(nil)就可以了。后面的block如果你在初始化的时候已经给过值的话，之后更新的时候只需要传nil就好了。
3.具体还是要根据应用场景来考虑，是用UIView还是用UIButton，UIView是通过直接updateCornerRadius实现，而UIButton则是通过setBackgroundImage来实现。

**Comment by CoderLwcXing** [comment]
OK，谢谢

**Comment by CoderLwcXing** [comment]
还有一个问题，就是 collectionviewcell 上的子 view UIImageView 进行圆角绘制，也是不生效的，是不是也是需要放到自己写的 VIew 上吗？因为 UIImageView 也是放在collectionviewcell上的

**Comment by qinqi777** [comment]
如果你的UIImageView的image来源于网络，那需要在图片下载完之后对图片进行处理，调用UIImage的对象方法addingCornerRadius来实现。假如你是用SDWebImage，你需要在完成的回调里面处理图片，并给ImageView重新赋值，还得注意弱引用，确实比较麻烦的。
如果上述方法比较麻烦，还是直接使用系统的layer.cornerRadius和clipToBounds来控制会更方便一些。不管是UIButton还是UIImageView

**Comment by CoderLwcXing** [comment]
好的，谢谢，我有试过通过 Image 来设置，但是发现很卡顿

**Comment by qinqi777** [comment]
GG
可能是很多cell同时处理图片，所有的图片放进内存扛不住的原因。这种情况还是使用系统的切割的方式吧layer.cornerRadius和clipToBounds
