### ISSUE TITLE
View里包含子View如果子VIew的宽高和父View等宽高，对外层View更新圆角，对子View不生效

### ISSUE THREAD

**Issue by cuixinle** [qinqi777/QQCorner#9]

**Comment by cuixinle** [comment]
实际上还是无法达到layer.mask+layer.masksToBounds的效果，这种情况如何解决

**Comment by qinqi777** [comment]
确实一个View不会影响到它所有的子View，因为这个原理是在View上盖了一层Layer，子视图不会受到影响的。
两个办法：
1、给需要被切割的子视图也用同样的方法加上圆角
2、直接用系统自带的layer.cornerRadius功能，配合view的clipToBounds或者layer的maskToBounds功能。
